# Menu Config
menu:
  HOME: /

# Side Message
aside:
  card_author:
    button:
      link: https://github.com/Lunaria-Moonstone/

# Image Config
index_img: transparent
footer_bg: transparent
background: url("https://s2.loli.net/2023/10/13/eibUCGpj2Qau58V.jpg")
mask:
  header: false

favicon: https://s2.loli.net/2023/10/13/OQZVm8c35ynbsFB.jpg

avatar:
  # img: /imgs/avatar.jpg
  img: https://s2.loli.net/2023/10/13/OQZVm8c35ynbsFB.jpg